language: php

php:
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
    - master
    - develop

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction

script:
  - bin/phpcs --standard=.phpcs.xml
  - bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  irc: "chat.freenode.net#thedevnetwork"
  email: vpassapera@gmail.com
