language: php

php:
  - 5.5
  - 5.6

branches:
  only:
    - master
    - develop

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpcs --standard=.phpcs.xml
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls

notifications:
  irc: "chat.freenode.net#thedevnetwork"
  email: vpassapera@gmail.com
